repos:
- repo: https://github.com/antonbabenko/pre-commit-terraform
  rev: v1.64.1 # Get the latest from: https://github.com/antonbabenko/pre-commit-terraform/releases
  hooks:
    - id: terraform_fmt
      name: Format Terraform
    - id: terraform_docs
      name: Update Terraform docs
    - id: terraform_tflint
      name: Initialize tflint 
      args: 
        - --args=--init
          